### ISSUE TITLE
xeus-zmq not found on MacOS

### ISSUE THREAD

**Issue by softstream-link** [jupyter-xeus/xeus-robot#100]
```yaml
channels:
  - conda-forge

name: xeus_robot_env

dependencies:
  - xeus-robot
  - jupyterlab=3
```

 Reason: tried: '.../micromamba/envs/xeus_robot_env/bin/../lib/libxeus-zmq.1.dylib' (no such file), '.../micromamba/envs/xeus_robot_env/bin/../lib/libxeus-zmq.1.dylib' (no such file), '/usr/local/lib/libxeus-zmq.1.dylib' (no such file), '/usr/lib/libxeus-zmq.1.dylib' (no such file, not in dyld cache)

Downgrading xeus-robot to =0.4.4 works but then you missing basic features such as robot output

Also upgrading to jupyterlab=4 losses syntax highlighting
